using System;
using System.Collections.Generic;

namespace backend.Modules.BusinessIntelligence.DTOs;

/// <summary>
/// Represents deep intelligence and trend analysis regarding business revenue.
/// </summary>
public class RevenueInsightDto
{
    /// <summary>
    /// Gets or sets total revenue generated in the current analysis timeframe.
    /// </summary>
    public decimal CurrentRevenue { get; set; }

    /// <summary>
    /// Gets or sets total revenue generated in the comparative previous timeframe.
    /// </summary>
    public decimal PreviousRevenue { get; set; }

    /// <summary>
    /// Gets or sets the percentage change in revenue compared to the prior period.
    /// </summary>
    public decimal PercentageChange { get; set; }

    /// <summary>
    /// Gets or sets whether revenue trend is positive, neutral, or declining.
    /// </summary>
    public string Trend { get; set; } = "Stable";

    /// <summary>
    /// Gets or sets the proportion of revenue generated by repeat vs. first-time customers.
    /// </summary>
    public decimal RepeatCustomerRevenuePercentage { get; set; }

    /// <summary>
    /// Gets or sets a descriptive narrative explaining key revenue drivers (e.g., "Sales increased because of repeat customers").
    /// </summary>
    public string PrimaryDriverExplanation { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets historical revenue data points for charting trends.
    /// </summary>
    public List<RevenueTrendPointDto> RevenueTrends { get; set; } = new();
}

/// <summary>
/// Represents a single time-series data point in a revenue trend graph.
/// </summary>
public class RevenueTrendPointDto
{
    /// <summary>
    /// Gets or sets the date or period label for this data point.
    /// </summary>
    public string Period { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the amount invoiced or captured in this period.
    /// </summary>
    public decimal Amount { get; set; }
}
