"use client";

import { useAiRecommendations, useApplyRecommendation } from "@/hooks/use-executive";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, CheckCircle2, AlertTriangle, ArrowRight } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";

export default function RecommendationsPage() {
  const { data: recommendations, isLoading } = useAiRecommendations();
  const { mutate: applyRecommendation, isPending: isApplying } = useApplyRecommendation();

  const handleApply = (id: string, title: string) => {
    applyRecommendation(id, {
      onSuccess: () => {
        toast.success(`Action applied: ${title}`);
      },
      onError: () => {
        toast.error(`Failed to apply action: ${title}`);
      }
    });
  };

  const pendingRecs = recommendations?.filter(r => !r.isApplied) || [];
  const appliedRecs = recommendations?.filter(r => r.isApplied) || [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Strategic Recommendations</h1>
        <p className="text-muted-foreground">Prioritized action items generated by the Executive Decision Engine.</p>
      </div>

      <h2 className="text-xl font-bold tracking-tight mt-8 mb-4 flex items-center gap-2">
        <AlertTriangle className="h-5 w-5 text-amber-500" /> Pending Actions ({pendingRecs.length})
      </h2>
      
      <div className="grid gap-6">
        {isLoading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-40 w-full" />
          ))
        ) : pendingRecs.length > 0 ? (
          pendingRecs.map((rec) => (
            <Card key={rec.id} className="border-l-4 border-l-amber-500">
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="text-lg flex items-center gap-2">
                      <Sparkles className="h-5 w-5 text-primary" />
                      {rec.title}
                    </CardTitle>
                    <CardDescription className="mt-1">{rec.category}</CardDescription>
                  </div>
                  <Badge variant={rec.priority.toLowerCase() === "high" ? "destructive" : "default"}>
                    {rec.priority} Priority
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-sm">{rec.description}</p>
                <div className="flex gap-6 text-sm">
                  <div>
                    <span className="text-muted-foreground">Estimated Impact:</span>
                    <span className="ml-2 font-semibold text-emerald-500">
                      ${rec.estimatedImpact.toLocaleString()}
                    </span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">AI Confidence:</span>
                    <span className="ml-2 font-semibold">{rec.confidenceLevel}%</span>
                  </div>
                </div>
                <div className="bg-muted/50 p-3 rounded-md text-sm">
                  <span className="font-semibold block mb-1">Suggested Action:</span>
                  {rec.suggestedAction}
                </div>
              </CardContent>
              <CardFooter className="bg-muted/20 border-t px-6 py-3 flex justify-end gap-2">
                <Button variant="outline" size="sm">Dismiss</Button>
                <Button 
                  size="sm" 
                  onClick={() => handleApply(rec.id, rec.title)}
                  disabled={isApplying}
                >
                  Apply Recommendation <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </CardFooter>
            </Card>
          ))
        ) : (
          <div className="text-center py-12 text-muted-foreground border rounded-lg bg-card/50">
            No pending recommendations. Your business is operating optimally!
          </div>
        )}
      </div>

      {appliedRecs.length > 0 && (
        <>
          <h2 className="text-xl font-bold tracking-tight mt-12 mb-4 flex items-center gap-2">
            <CheckCircle2 className="h-5 w-5 text-emerald-500" /> Recently Applied
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {appliedRecs.map(rec => (
              <Card key={rec.id} className="opacity-75">
                <CardHeader className="pb-2">
                  <CardTitle className="text-base line-through text-muted-foreground">{rec.title}</CardTitle>
                  <CardDescription>Applied on {rec.appliedAt ? format(new Date(rec.appliedAt), "MMM dd, yyyy") : "Recently"}</CardDescription>
                </CardHeader>
              </Card>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
