"use client";

import { useState } from "react";
import { useLatestForecast, useGenerateForecast } from "@/hooks/use-executive";
import { ForecastChart } from "@/components/executive/forecast-chart";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { format, addMonths } from "date-fns";
import { RefreshCw, TrendingUp } from "lucide-react";
import { toast } from "sonner";

export default function ForecastingPage() {
  const [metric, setMetric] = useState("revenue");
  const { data: forecast, isLoading: forecastLoading } = useLatestForecast(metric);
  const { mutate: generateForecast, isPending: isGenerating } = useGenerateForecast();

  const handleGenerate = () => {
    generateForecast(metric, {
      onSuccess: () => toast.success(`${metric} forecast generated successfully.`),
      onError: () => toast.error(`Failed to generate ${metric} forecast.`)
    });
  };

  // Mock historical data to attach the forecast to for visualization purposes
  const generateMockTrendData = () => {
    if (!forecast) return [];
    
    const data = [];
    let currentVal = forecast.predictedValue * 0.7; // Start lower
    
    for (let i = 5; i >= 1; i--) {
      data.push({
        dateLabel: format(addMonths(new Date(), -i), "MMM yyyy"),
        actual: currentVal,
        forecast: null,
        lower: null,
        upper: null
      });
      currentVal = currentVal * 1.05; // 5% growth
    }
    
    // Add the current month (where actual meets forecast)
    data.push({
      dateLabel: format(new Date(), "MMM yyyy"),
      actual: currentVal,
      forecast: currentVal,
      lower: currentVal,
      upper: currentVal
    });

    // Add the forecasted month
    data.push({
      dateLabel: format(new Date(forecast.targetDate), "MMM yyyy"),
      actual: null,
      forecast: forecast.predictedValue,
      lower: forecast.lowerBound,
      upper: forecast.upperBound
    });

    return data;
  };

  const chartData = generateMockTrendData();

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Forecasting</h1>
          <p className="text-muted-foreground">Predict future trends using historical data and AI models.</p>
        </div>
        <div className="flex gap-2">
          {["revenue", "expenses", "profit"].map(m => (
            <Button 
              key={m} 
              variant={metric === m ? "default" : "outline"}
              onClick={() => setMetric(m)}
              className="capitalize"
            >
              {m}
            </Button>
          ))}
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="col-span-1">
          <CardHeader>
            <CardTitle className="capitalize">{metric} Forecast Details</CardTitle>
            <CardDescription>Generated by {forecast?.modelUsed || "AI_ARIMA_V1"}</CardDescription>
          </CardHeader>
          <CardContent>
            {forecastLoading ? (
              <div className="space-y-4">
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-full" />
              </div>
            ) : forecast ? (
              <div className="space-y-6">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Predicted Value</p>
                  <div className="text-3xl font-bold text-primary flex items-center gap-2 mt-1">
                    <TrendingUp className="h-6 w-6" />
                    ${forecast.predictedValue.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4 border-t pt-4">
                  <div>
                    <p className="text-xs font-medium text-muted-foreground">Lower Bound</p>
                    <p className="text-lg font-semibold">${forecast.lowerBound.toLocaleString(undefined, { maximumFractionDigits: 0 })}</p>
                  </div>
                  <div>
                    <p className="text-xs font-medium text-muted-foreground">Upper Bound</p>
                    <p className="text-lg font-semibold">${forecast.upperBound.toLocaleString(undefined, { maximumFractionDigits: 0 })}</p>
                  </div>
                </div>
                <div className="border-t pt-4">
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-muted-foreground">Confidence Score</span>
                    <span className="font-medium text-emerald-500">{forecast.confidenceScore}%</span>
                  </div>
                  <div className="w-full bg-secondary h-2 rounded-full mt-2">
                    <div className="bg-emerald-500 h-2 rounded-full" style={{ width: `${forecast.confidenceScore}%` }} />
                  </div>
                </div>
                <Button 
                  className="w-full" 
                  onClick={handleGenerate} 
                  disabled={isGenerating}
                >
                  <RefreshCw className={`mr-2 h-4 w-4 ${isGenerating ? "animate-spin" : ""}`} />
                  Regenerate Forecast
                </Button>
              </div>
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <p>No forecast available.</p>
                <Button className="mt-4" onClick={handleGenerate} disabled={isGenerating}>Generate Now</Button>
              </div>
            )}
          </CardContent>
        </Card>

        <div className="col-span-1 md:col-span-2">
          {forecastLoading ? (
            <Skeleton className="h-[450px] w-full" />
          ) : (
            <ForecastChart 
              title={`${metric.charAt(0).toUpperCase() + metric.slice(1)} Forecast Trend`}
              description={`Projected values for ${forecast ? format(new Date(forecast.targetDate), "MMMM yyyy") : "next period"}`}
              data={chartData}
              xKey="dateLabel"
              actualKey="actual"
              forecastKey="forecast"
              lowerBoundKey="lower"
              upperBoundKey="upper"
            />
          )}
        </div>
      </div>
    </div>
  );
}
