using backend.Modules.AiAgent.ToolRegistry.Interfaces;
using backend.Modules.AiAgent.ToolRegistry.Models;
using backend.Modules.BusinessIntelligence.Entities;
using backend.Persistence;

namespace backend.Modules.AiAgent.ToolRegistry.Tools;

public class ReportTool : ITool
{
    private readonly ApplicationDbContext _context;

    public ReportTool(ApplicationDbContext context)
    {
        _context = context;
    }

    public string Name => "ReportTool";
    public string Description => "Business Report Tool: generate executive reports, weekly performance, and financial summaries.";
    public string Category => "BusinessIntelligence";
    public string[] RequiredPermissions => new[] { "BI.View", "BI.Create" };
    public bool IsDestructive => false;
    public string ParametersSchema => "{\"type\":\"object\",\"properties\":{\"reportType\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"}}}";

    public async Task<ToolResult> ExecuteAsync(
        ToolExecutionContext context,
        IDictionary<string, object> parameters,
        CancellationToken cancellationToken = default)
    {
        var reportType = parameters.TryGetValue("reportType", out var typeObj) ? typeObj?.ToString() : "Weekly Performance";
        var title = parameters.TryGetValue("title", out var titleObj) ? titleObj?.ToString() : $"{reportType} Report";

        var report = new Report
        {
            Id = Guid.NewGuid(),
            OrganizationId = context.OrganizationId,
            Name = title ?? "AI Executive Report",
            ReportType = reportType ?? "Executive",
            GeneratedBy = context.UserId,
            Filters = "{\"summary\":\"Weekly revenue, lead conversion, and team performance report generated by AI Business Agent.\",\"status\":\"Optimal\"}",
            Format = "PDF",
            FileUrl = $"/reports/{Guid.NewGuid():N}.pdf"
        };

        await _context.Reports.AddAsync(report, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);

        return ToolResult.Ok($"Report '{report.Name}' generated successfully.", new { report.Id, Title = report.Name, report.ReportType, report.FileUrl, report.CreatedAt });
    }
}
