using System.Text.Json;
using backend.Interfaces;
using backend.Modules.CRM.Entities;
using backend.Modules.CustomerJourney.Interfaces;
using backend.Modules.Forms.DTOs;
using backend.Modules.Forms.Entities;
using backend.Modules.Forms.Interfaces;
using backend.Modules.LeadCapture.Interfaces;
using backend.Modules.Webhooks.Interfaces;

namespace backend.Modules.LeadCapture.Services;

public class LeadCaptureService : ILeadCaptureService
{
    private readonly ISubmissionRepository _submissionRepository;
    private readonly IGenericRepository<Lead> _leadRepository;
    private readonly IJourneyRepository _journeyRepository;
    private readonly IWebhookDispatchService _webhookDispatchService;
    private readonly IUnitOfWork _unitOfWork;

    public LeadCaptureService(
        ISubmissionRepository submissionRepository,
        IGenericRepository<Lead> leadRepository,
        IJourneyRepository journeyRepository,
        IWebhookDispatchService webhookDispatchService,
        IUnitOfWork unitOfWork)
    {
        _submissionRepository = submissionRepository;
        _leadRepository = leadRepository;
        _journeyRepository = journeyRepository;
        _webhookDispatchService = webhookDispatchService;
        _unitOfWork = unitOfWork;
    }

    public async Task HandleFormSubmissionAsync(Guid organizationId, Guid formId, SubmitFormDto dto, string device, string browser, CancellationToken cancellationToken = default)
    {
        // 1. Create Form Submission Record
        var submission = new FormSubmission
        {
            OrganizationId = organizationId,
            FormId = formId,
            SubmittedData = dto.SubmittedData,
            Source = dto.Source,
            Device = device,
            Browser = browser,
            SubmittedAt = DateTime.UtcNow
        };

        await _submissionRepository.AddAsync(submission, cancellationToken);

        // 2. Parse Submission Data to extract Lead details (simplistic extraction for MVP)
        var parsedData = TryParseJson(dto.SubmittedData);
        var firstName = GetStringValue(parsedData, "firstName", "first_name", "FirstName") ?? "Unknown";
        var lastName = GetStringValue(parsedData, "lastName", "last_name", "LastName") ?? "";
        var email = GetStringValue(parsedData, "email", "Email") ?? "";
        var phone = GetStringValue(parsedData, "phone", "Phone", "phoneNumber") ?? "";
        var company = GetStringValue(parsedData, "company", "Company", "companyName") ?? "";

        // 3. Create CRM Lead automatically
        var lead = new Lead
        {
            OrganizationId = organizationId,
            FirstName = firstName,
            LastName = lastName,
            Email = email,
            Phone = phone,
            CompanyName = company,
            Source = dto.Source,
            Status = backend.Modules.CRM.Enums.LeadStatus.New
        };

        await _leadRepository.AddAsync(lead, cancellationToken);

        // Link submission to lead
        submission.CRMLeadId = lead.Id; // Note: we need to ensure Id gets generated or we set it manually. By default Guid is auto-generated by EF on Add, but safely we should save changes first if we rely on DB generated IDs. For Guid, it might be 0000.. until saved unless initialized. We can initialize it or let EF do it. EF will generate it on Add if configured, but let's assign explicitly.
        lead.Id = Guid.NewGuid();
        submission.CRMLeadId = lead.Id;

        // 4. Start Customer Journey
        var journey = new backend.Modules.CustomerJourney.Entities.CustomerJourney
        {
            OrganizationId = organizationId,
            LeadId = lead.Id,
            PreviousStage = string.Empty,
            CurrentStage = "Lead",
            EnteredAt = DateTime.UtcNow
        };

        await _journeyRepository.AddAsync(journey, cancellationToken);

        // 5. Commit all to DB
        await _unitOfWork.CompleteAsync(cancellationToken);

        // 6. Trigger Webhooks and AI Automation (async)
        // Fire-and-forget webhook event
        _ = _webhookDispatchService.EnqueueEventAsync(organizationId, "FormSubmitted", new
        {
            FormId = formId,
            LeadId = lead.Id,
            Source = dto.Source,
            Data = parsedData
        }, CancellationToken.None);
        
        _ = _webhookDispatchService.EnqueueEventAsync(organizationId, "LeadCreated", new
        {
            LeadId = lead.Id,
            Email = lead.Email,
            Name = $"{lead.FirstName} {lead.LastName}",
            Source = lead.Source
        }, CancellationToken.None);
    }

    private static Dictionary<string, string> TryParseJson(string json)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(json)) return new Dictionary<string, string>();
            return JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? new Dictionary<string, string>();
        }
        catch
        {
            return new Dictionary<string, string>();
        }
    }

    private static string? GetStringValue(Dictionary<string, string> dict, params string[] keys)
    {
        foreach (var key in keys)
        {
            var matchedKey = dict.Keys.FirstOrDefault(k => string.Equals(k, key, StringComparison.OrdinalIgnoreCase));
            if (matchedKey != null && dict.TryGetValue(matchedKey, out var value) && !string.IsNullOrWhiteSpace(value))
            {
                return value;
            }
        }
        return null;
    }
}
